db_configsystems={
    "Teradata": "DATABASE_SYSTEM",
    "Informix": "DATABASE_SYSTEM",
    "MS SQL Server Always On": "DATABASE_SYSTEM",
    "DB2 Purescale": "DATABASE_SYSTEM",
    "MariaDB": "DATABASE_SYSTEM",
    "Sybase IQ": "DATABASE_SYSTEM",
    "Aster": "DATABASE_SYSTEM",
    "IBM DB2 for zOS": "DATABASE_SYSTEM",
    "PostgreSQL": "DATABASE_SYSTEM",
    "Redis": "DATABASE_SYSTEM",
    "Elasticsearch": "DATABASE_SYSTEM",
    "Cloudera": "DATABASE_SYSTEM",
    "Oracle Exadata": "DATABASE_SYSTEM",
    "Hortonworks": "DATABASE_SYSTEM",
    "Neo4j": "DATABASE_SYSTEM",
    "PerconaMySQL": "DATABASE_SYSTEM",
    "MemSQL": "DATABASE_SYSTEM",
    "Cassandra  Datastax": "DATABASE_SYSTEM",
    "SAP HANA": "DATABASE_SYSTEM",
    "Yugabyte": "DATABASE_SYSTEM",
    "MS SQL Server": "DATABASE_SYSTEM",
    "Couch": "DATABASE_SYSTEM",
    "Datasets for zOS": "DATABASE_SYSTEM",
    "CockroachDB": "DATABASE_SYSTEM",
    "Cassandra Apache": "DATABASE_SYSTEM",
    "MongoDB": "DATABASE_SYSTEM",
    "Oracle": "DATABASE_SYSTEM",
    "Couchbase": "DATABASE_SYSTEM",
    "DB2": "DATABASE_SYSTEM",
    "Greenplum": "DATABASE_SYSTEM",
    "MySQL": "DATABASE_SYSTEM",
    "OpenSearch": "DATABASE_SYSTEM",
    "Sybase ASE": "DATABASE_SYSTEM",
    "MS SQL Server Cluster": "DATABASE_SYSTEM",
    "Oracle RAC": "DATABASE_SYSTEM",
    "Netezza": "DATABASE_SYSTEM",
    "Vertica": "DATABASE_SYSTEM",
    "Cassandra": "DATABASE_SYSTEM",
    "IMS for zOS": "DATABASE_SYSTEM",
    "Amazon Aurora MySQL": "DATABASE_SYSTEM",
    "Amazon Aurora PostgreSQL": "DATABASE_SYSTEM",
    "Amazon RDS for Oracle": "DATABASE_SYSTEM",
    "AWS Fargate": "DATABASE_SYSTEM",
    "Amazon DynamoDB": "DATABASE_SYSTEM",
    "Amazon ElastiCache for Redis": "DATABASE_SYSTEM",
    "Amazon RDS for MariaDB": "DATABASE_SYSTEM",
    "Amazon RDS for Microsoft SQL Server": "DATABASE_SYSTEM",
    "Amazon RDS for MySQL": "DATABASE_SYSTEM",
    "Amazon RDS for PostgreSQL": "DATABASE_SYSTEM",
    "Amazon Redshift": "DATABASE_SYSTEM",
    "Amazon S3": "DATABASE_SYSTEM",
    "MongoDB Atlas": "DATABASE_SYSTEM",
    "Snowflake": "DATABASE_SYSTEM",
    "Amazon RDS for Aurora Postgres": "DATABASE_SYSTEM",
    "Amazon RDS for Postgres": "DATABASE_SYSTEM",
    "AmazonRDS for SQL Server": "DATABASE_SYSTEM",
    "DocumentDB": "DATABASE_SYSTEM",
    "Neptune": "DATABASE_SYSTEM",
    "Azure Cassandra": "DATABASE_SYSTEM",
    "Azure Cosmos Gremlin": "DATABASE_SYSTEM",
    "Azure Cosmos SQL": "DATABASE_SYSTEM",
    "Azure Cosmos Table": "DATABASE_SYSTEM",
    "Azure SQL": "DATABASE_SYSTEM",
    "Azure Synapse Analytics": "DATABASE_SYSTEM",
    "Azure Apache Solr": "DATABASE_SYSTEM",
    "Azure Cosmos": "DATABASE_SYSTEM",
    "Azure Database for PostgreSQL": "DATABASE_SYSTEM",
    "Azure MySQL": "DATABASE_SYSTEM",
    "Google Cloud BigQuery": "DATABASE_SYSTEM",
    "Google Cloud PostgreSQL": "DATABASE_SYSTEM",
    "Google Cloud SQL": "DATABASE_SYSTEM",
    "Google Cloud Apache Solr": "DATABASE_SYSTEM",
    "Google Cloud Firebase": "DATABASE_SYSTEM",
    "Google Cloud Firestore": "DATABASE_SYSTEM",
    "Google Cloud MSSQL": "DATABASE_SYSTEM",
    "Google Cloud MySQL": "DATABASE_SYSTEM",
    "Google Cloud Spanner": "DATABASE_SYSTEM",
    "IBM DB2 Warehouse": "DATABASE_SYSTEM",
    "Oracle Autonomous Database": "DATABASE_SYSTEM",
    "Apache Cassandra": "DATABASE_SYSTEM",
    "CouchDB": "DATABASE_SYSTEM",
    "EDB Postgres": "DATABASE_SYSTEM",
    "Fujistu": "DATABASE_SYSTEM",
    "HDFS": "DATABASE_SYSTEM",
    "Intersystems IRIS": "DATABASE_SYSTEM",
    "ScyllaDB": "DATABASE_SYSTEM"
}