input_csv_path: consolidation-script2/data/input/OnPrem_UC.csv
dbinfo_csv_path: consolidation-script2/data/input/OnPrem_UC_Dbinfo.csv
output_csv_path: consolidation-script2/data/output/csv/OnPrem_UC.csv
output_json_path: src/data/consolidated_jsons/OnPrem_UC.json
environment_name: On-premise or IaaS
method_name: Universal Connector
compat_header:
  - GDP_Type
  - Guardium_Version
  - DataSource
  - DataSource_Version
feature_header:
  - VA_supported
  - Classification_supported
  - Notes
  - Download_URL
  - Readme_URL
partition_header: 2