full_csv_path: data/input/supported_dbs_mongo.csv
output_csv_path: data/output/supported_dbs_mongo_consolidated.csv
output_json_path: data/output/supported_dbs_mongo_consolidated.json
compat_header:
  - GuardiumVersion
  - OSName
  - OSVersion
  - DatabaseName
  - DatabaseVersion
feature_header:
  -  Network traffic
  -  Local traffic
  -  Encrypted traffic
  -  Shared Memory
  -  Kerberos
  -  Blocking
  -  Redaction
  -  UID Chain
  -  Compression
  -  Query Rewrite
  -  Instance Discovery
  -  Protocol
  -  Notes
partition_header: 3