full_csv_path: consolidation-script2/data/input/OnPrem_UC.csv
output_csv_path: consolidation-script2/data/output/csv/OnPrem_UC.csv
output_json_path: src/data/consolidated_csvs/OnPrem_UC.json
compat_header:
  - GuardiumVersion
  - OSName
  - OSVersion
  - DatabaseName
  - DatabaseVersion
feature_header:
  -  Network traffic
  -  Instance Discovery
  -  Protocol
  -  Notes
partition_header: 3