output_csv_path: data/output/csv/Azure_UC.csv
output_json_path: data/output/json/Azure_UC.json
full_csv_path: data/input/Azure_UC.csv
compat_header:
  -  GDP_Type
  -  Guardium_Version
  -  DataSource
  -  DataSource_Version
feature_header:
  -  VA_supported
  -  Classification_supported
  -  Notes
  -  Download_URL
  -  Readme_URL
partition_header: 2
