output_csv_path: data/output/csv/AWS_AmKin.csv
output_json_path: data/output/json/AWS_AmKin.json
full_csv_path: data/input/AWS_AmKin.csv
compat_header:
  -  GDP version
  -  GI version
  -  Data source
  -  Data source version
feature_header:
  -  VA supported
  -  Classification supported
  -  Notes
  -  Download URL
  -  Readme URL
partition_header: 2
