full_csv_path: data/input/OracleCloud_ExStap.csv
output_csv_path: data/output/csv/OracleCloud_ExStap.csv
output_json_path: data/output/json/OracleCloud_ExStap.json
compat_header:
  -  GDP version
  -  GI version
  -  Data source
  -  Data source version
feature_header:
  -  VA supported
  -  Classification supported
  -  Notes
  -  Download URL
  -  Readme URL
partition_header: 2