output_csv_path: consolidation-script2/data/output/csv/example.csv
output_json_path: consolidation-script2/data/output/json/example.json
input_csv_path: consolidation-script2/data/input/example.csv
environment_name: Example
method_name: Example
compat_header:
  - GuardiumVersion
  - DatabaseName
  - DatabaseVersion
  - OSName
  - OSVersion
feature_header:
  - Feature
partition_header: 1
