output_csv_path: data/output/csv/AWS_UC.csv
output_json_path: data/output/json/AWS_UC.json
full_csv_path: data/input/AWS_UC.csv
compat_header:
  -  GDP_Version
  -  GI_Version
  -  DataSource
  -  DataSource_Version
feature_header:
  -  VA_supported
  -  Classification_supported
  -  Notes
  -  Download_URL
  -  Readme_URL
partition_header: 2