output_csv_path: consolidation-script2/data/output/csv/IBMCloud_UC.csv
output_json_path: src/data/consolidated_jsons/IBMCloud_UC.json
input_csv_path: consolidation-script2/data/input/IBMCloud_UC.csv
environment_name: IBM Cloud (Database as a Service)
method_name: Universal Connector
compat_header:
  - GDP_Type
  - Guardium_Version
  - DataSource
  - DataSource_Version
feature_header:
  - VA_supported
  - Classification_supported
  - Notes
  - Download_URL
  - Readme_URL
partition_header: 2
