output_csv_path: data/output/csv/GCP_ExStap.csv
output_json_path: data/output/json/GCP_ExStap.json
full_csv_path: data/input/GCP_ExStap.csv
compat_header:
  -  GDP version
  -  GI version
  -  Data source
  -  Data source version
feature_header:
  -  VA supported
  -  Classification supported
  -  Notes
  -  Download URL
  -  Readme URL
partition_header: 2
