output_csv_path: data/output/csv/example.csv
output_json_path: data/output/json/example.json
full_csv_path: data/input/example.csv
compat_header:
  -  GuardiumVersion
  -  DatabaseName
  -  DatabaseVersion
  -  OSName
  - OSVersion
feature_header:
  -  Feature
partition_header: 3
