output_csv_path: data/output/csv/IBMCloud_ExStap.csv
output_json_path: data/output/json/IBMCloud_ExStap.json
full_csv_path: data/input/IBMCloud_ExStap.csv
compat_header:
  -  GDP_Type
  -  Guardium_Version
  -  DataSource
  -  DataSource_Version
feature_header:
  -  VA_supported
  -  Classification_supported
  -  Notes
partition_header: 2
