input_csv_path: consolidation-script2/data/input/OnPrem_Stap.csv
output_csv_path: consolidation-script2/data/output/csv/OnPrem_Stap.csv
dbinfo_csv_path: consolidation-script2/data/input/OnPrem_Stap_Dbinfo.csv
output_json_path: src/data/consolidated_jsons/OnPrem_Stap.json
environment_name: On-premise or IaaS
method_name: STAP
compat_header:
  - GDP_Type
  - GuardiumVersion
  - OSName
  - OSVersion
  - DatabaseName
  - DatabaseVersion
feature_header:
  - Network traffic
  - Local traffic
  - Encrypted traffic
  - Shared Memory
  - Kerberos
  - Blocking
  - Redaction
  - UID Chain
  - Compression
  - Query Rewrite
  - Instance Discovery
  - Protocol
  - Notes
partition_header: 4
