output_csv_path: consolidation-script2/data/output/csv/AWS_AmKin.csv
output_json_path: src/data/consolidated_jsons/AWS_AmKin.json
input_csv_path: consolidation-script2/data/input/AWS_AmKin.csv
environment_name: AWS (Database as a Service)
method_name: Amazon Kinesis
compat_header:
  - GDP_Type
  - Guardium_Version
  - DataSource
  - DataSource_Version
feature_header:
  - VA_supported
  - Classification_supported
  - Notes
  - Download_URL
  - Readme_URL
partition_header: 2
